import styles from '../styles/Home.module.scss'

import Head from 'next/head'
import nookies from 'nookies'
import { AxiosError } from "axios"
import { GetServerSideProps } from 'next'

import PostMessagers from '../components/home/PostMessangers'
import Menssagers from '../components/home/Menssagers'
import fetchApi  from "../apis/fetchApi"

export default function Home() {

  return (
    <div className={"d-flex  "+styles.main}>
      <Head>
        <title>Reths social media</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className={"container h-100 justify-content-center "+styles.container}>
        <div className='pt-4'>
          <PostMessagers />    
        </div>
        <div className="h-100 pt-4">
          <Menssagers />
        </div>
      </div>


    </div>
  )
}


export async function getServerSideProps(context: any) {

  try{
    const cookie = nookies.get(context)
    const token =  cookie["reths-social-media-token"]

    var response = await fetchApi.post("/auth/token-valid",{

        },{headers: {authorization: token} })

  }catch(error){
      return {
        redirect: {
          destination: "/login"
        }
      }
  }



  return {
    props: {}, 
  }
}
